name: Release Go Project

on:
  push:
    tags:
      - "v*" # 当推送包含 v 开头的tag时触发，例如 v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # 设置你需要的 Go 版本

      - name: Build
        run: |
          # 为不同平台编译，根据你的需求修改
          GOOS=linux GOARCH=amd64 go build -o build/gos-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o build/gos-windows-amd64.exe

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app-linux-amd64
            build/app-windows-amd64.exe
            build/app-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}