name: Release Go Project

on:
  workflow_dispatch:
  push:
    tags:
      - "v*" # 当推送包含 v 开头的tag时触发，例如 v1.0.0

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # 设置你需要的 Go 版本

      - name: Build
        run: |
          # 为不同平台编译，根据你的需求修改
          GOOS=linux GOARCH=amd64 go build -o build/gos-linux-amd64 ./cmd/gos/gos.go
          GOOS=linux GOARCH=arm64 go build -o build/gos-linux-arm64 ./cmd/gos/gos.go
          GOOS=windows GOARCH=amd64 go build -o build/gos-windows-amd64.exe ./cmd/gos/gos.go
          GOOS=windows GOARCH=arm64 go build -o build/gos-windows-arm64.exe ./cmd/gos/gos.go

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/gos-linux-amd64
            build/gos-linux-arm64
            build/gos-windows-amd64.exe
            build/gos-windows-arm64.exe
